--pIVOT TABLE TO SHOW MONTHS AS COLUMNS

SELECT 
    YEAR(ORDERDATE) AS year,
    SUM(CASE WHEN MONTH(ORDERDATE) = 1 THEN Sales ELSE 0 END) AS Jan,
    SUM(CASE WHEN MONTH(ORDERDATE) = 2 THEN Sales ELSE 0 END) AS Feb,
    SUM(CASE WHEN MONTH(ORDERDATE) = 3 THEN Sales ELSE 0 END) AS Mar
    -- add up to Dec
FROM Online_Sales_Data
GROUP BY YEAR(ORDERDATE)
ORDER BY year;